version: '3.4'

services:
  database:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: nghia14302
      MYSQL_USER: fcode-member-card
      MYSQL_PASSWORD: f-code.tech
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./dump:/docker-entrypoint-initdb.d
  membercard:
    image: nghia14302/fcode-member-card
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    expose:
      - "4000"
    restart: always
volumes:
  db-config:
  db-data:
