-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 23:22:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fcode_member_card
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fcode_member_card
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS `fcode_member_card` DEFAULT CHARACTER
SET utf8 ;
USE `fcode_member_card`
;

-- -----------------------------------------------------
-- Table `fcode_member_card`.`member`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `fcode_member_card`.`member`
(
  `id` VARCHAR
(64) NOT NULL,
  `member_id` VARCHAR
(12) NOT NULL,
  `first_name` VARCHAR
(45) NOT NULL,
  `last_name` VARCHAR
(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `school_mail` VARCHAR
(50) NULL,
  `personal_mail` VARCHAR
(50) NOT NULL,
  `phone` VARCHAR
(10) NOT NULL,
  `major` VARCHAR
(45) NULL,
  `session_year` VARCHAR
(45) NOT NULL,
  `position` VARCHAR
(45) NOT NULL DEFAULT 'member',
  `facebook` VARCHAR
(100) NULL,
  `portfolio_id` VARCHAR
(45) NULL,
  `active_point` INT NOT NULL DEFAULT 0,
  `avartar` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY
(`id`),
  UNIQUE INDEX `id_UNIQUE`
(`id` ASC) VISIBLE,v
  UNIQUE INDEX `phone_UNIQUE`
(`phone` ASC) VISIBLE,
  UNIQUE INDEX `personal_mail_UNIQUE`
(`personal_mail` ASC) VISIBLE,
  UNIQUE INDEX `school_mail_UNIQUE`
(`school_mail` ASC) VISIBLE,
  UNIQUE INDEX `facebook_UNIQUE`
(`facebook` ASC) VISIBLE,
  UNIQUE INDEX `member_id_UNIQUE`
(`member_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcode_member_card`.`event`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `fcode_member_card`.`event`
(
  `id` VARCHAR
(50) NOT NULL,
  `name` VARCHAR
(100) NOT NULL,
  `date` DATE NOT NULL,
  `description` LONGTEXT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NULL,
  `status` VARCHAR
(45) NOT NULL,
  `semester` VARCHAR
(45) NOT NULL,
  PRIMARY KEY
(`id`),
  UNIQUE INDEX `id_UNIQUE`
(`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcode_member_card`.`attendance`
-- -----------------------------------------------------
CREATE TABLE
IF NOT EXISTS `fcode_member_card`.`attendance`
(
  `member_id` VARCHAR
(50) NOT NULL,
  `event_id` VARCHAR
(50) NOT NULL,
  `status` VARCHAR
(45) NOT NULL DEFAULT 'NOT YET',
  PRIMARY KEY
(`member_id`, `event_id`),
  INDEX `fk_member_has_event_event1_idx`
(`event_id` ASC) VISIBLE,
  INDEX `fk_member_has_event_member_idx`
(`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_member_has_event_member`
    FOREIGN KEY
(`member_id`)
    REFERENCES `fcode_member_card`.`member`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_event_event1`
    FOREIGN KEY
(`event_id`)
    REFERENCES `fcode_member_card`.`event`
(`id`)
    ON
DELETE NO ACTION
    ON
UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO member
VALUES
  ('SE160050', 'SE160050', 'Cao Nguyễn Hoàng', 'Hiệp', '2002-12-22 00:00:00', 'hiepcnhse160050@fpt.edu.vn', 'cnhh85@gmail.com', 0866827256, 'null', 'K16', 'member', 'https://www.facebook.com/sirhiepop/', 'null', 0, 'null'),
  ('SE161180', 'SE161180', 'Nguyễn Trọng', 'Nghĩa', '2002-12-23 00:00:00', 'nghiantse161180@fpt.edu.vn', 'nghia14302', 0947562592, 'null', 'K16', 'member', 'https://www.facebook.com/DVIL.NTN/', 'null', 0, 'null'),
  ('SE160046', 'SE160046', 'Huỳnh Hoàng', 'Huy', '2002-12-27 00:00:00', 'huyhhse160046@fpt.edu.vn', 'huynhhuy2002@gmail.com', 0905873846, 'null', 'K16', 'member', 'https://www.facebook.com/kr.nzk', 'null', 0, 'null'),
  ('SE161268', 'SE161268', 'Lý Tuấn', 'Kiệt', '2003-01-09 00:00:00', 'kietltse161268@fpt.edu.vn', 'lyhung998877@gmail.com', 0966319365, 'null', 'K16', 'member', 'fb.me/tuankiet2s', 'null', 0, 'null');

SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
