require('dotenv').config();

const {
	MYSQL_USERNAME,
	MYSQL_PASSWORD,
	MYSQL_DATABASE,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	HOST_URL,
} = process.env;
module.exports = {
	MYSQL_USERNAME,
	MYSQL_PASSWORD,
	MYSQL_DATABASE,
	GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET,
	HOST_URL,
};
